export const ORDER_STATUS = Object.freeze({
  PENDING: "PENDING",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  CONFIRMED: "CONFIRMED",
  PAID: "PAID",
  CANCELLED: "CANCELLED"
});

export const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  PAID: "PAID",
  FAILED: "FAILED"
});

export const PAYMENT_METHOD = Object.freeze({
  PAYMENT_ON_CHECKIN: "PAYMENT_ON_CHECKIN",
  PAYMENT_IN_ADVANCE: "PAYMENT_IN_ADVANCE",
});
export const ORDER_TYPE = Object.freeze({
  ROOM_ORDER: "ROOM_ORDER",
  PRODUCT_ORDER: "PRODUCT_ORDER",
});
